// Automatically generated by the Tiger compiler, do NOT edit.

	.data
slp_format:
	.string "%d "
newline:
	.string "\n"
exception:
	.string "\divide by zero"


	.text
	.globl main
main:
	pushl	%ebp
	movl	%esp, %ebp
	pushl	$exception
	call	printf
	addl	$4, %esp
	leave
	ret

