package slp;

import slp.Slp2.Exp;
import slp.Slp2.Exp.*;
import slp.Slp2.Stm;
import util.Todo;

import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.util.HashSet;
import java.util.List;

// a simple compiler for SLP, to x64.
public class Compiler {
    // ////////////////////////////////////////
    // whether to keep the generated assembly file.
    boolean keepAsm = false;
    String asmFile = "/tmp/slp_out.s";
    String outFile = asmFile + ".out";
    HashSet<String> ids;
    StringBuffer buf;

    private void emit(String s) {
        buf.append(s);
    }

    private void compileExp(Exp exp) {
        switch (exp) {
            case Id(String x) -> {
                emit("\tleaq\t" + x + "(%rip), %rax\n");
                emit("\tmovq\t(%rax), %rax\n");
            }
            case Num(int n) -> emit("\tmovq\t$" + n + ", %rax\n");
            case Op(
                    Exp left,
                    String op,
                    Exp right
            ) -> {
                compileExp(left);
                emit("\tpushq\t%rax\n");
                compileExp(right);
                emit("\tpopq\t%rdx\n");
                switch (op) {
                    case "+" -> emit("\taddq\t%rdx, %rax\n");
                    case "-" -> {
                        emit("\tsubq\t%rax, %rdx\n");
                        emit("\tmovq\t%rdx, %rax\n");
                    }
                    case "*" -> emit("\timulq\t%rdx\n");
                    default -> throw new Todo(op);
                }
            }
            case Eseq(
                    Stm s,
                    Exp e
            ) -> {
                compileStm0(s);
                compileExp(e);
            }
        }
    }

    // to compile a statement
    private void compileStm0(Stm s) {
        switch (s) {
            case Stm.Compound(
                    Stm s1,
                    Stm s2
            ) -> {
                compileStm0(s1);
                compileStm0(s2);
            }
            case Stm.Assign(
                    String x,
                    Exp e
            ) -> {
                ids.add(x);
                compileExp(e);
                emit("\tleaq\t" + x + "(%rip), %rdx\n");
                emit("\tmovq\t%rax, (%rdx)\n");
            }
            case Stm.Print(List<Exp> exps) -> {
                var prefix = exps.subList(0, exps.size() - 1);
                var last = exps.getLast();
                prefix.forEach(e -> {
                    compileExp(e);
                    emit("""
                                movq\t%rax, %rsi
                                leaq\tslp_format(%rip), %rdi
                                callq\tprintf
                            """);
                });
                compileExp(last);
                emit("""
                            movq\t%rax, %rsi
                            leaq\tslp_format_no_blank(%rip), %rdi
                            callq\tprintf
                        """);
                emit("""
                            leaq\tnew_line(%rip), %rdi
                            callq\tprintf
                        """);
            }
        }
    }

    // ////////////////////////////////////////
    public String compileStm(Stm prog, StringBuffer sb) throws Exception {
        // we always reset these two variables, so that this
        // method is re-entrant.
        this.ids = new HashSet<>();
        this.buf = new StringBuffer();

        // do the real work
        compileStm0(prog);

        FileWriter fileWriter = new FileWriter(asmFile);
        fileWriter.write(
                """
                        // Automatically generated by the Tiger compiler, do NOT edit.
                        // name mangling:
                        .set main, _main
                        .set printf, _printf
                        //
                        // the data section:
                            .data
                        slp_format:
                            .string "%d "
                        slp_format_no_blank:
                            .string "%d"
                        new_line:
                            .string "\\n"
                        """);
        for (String s : this.ids) {
            fileWriter.write(s + ":");
            fileWriter.write("\t.long 0\n");
        }
        fileWriter.write(
                """
                            .text
                            .globl _main
                        _main:
                            pushq\t%rbp
                            movq\t%rsp, %rbp
                        """);
        fileWriter.write(buf.toString());
        fileWriter.write("\tleave\n\tret\n\n");
        fileWriter.close();

        // compile this asm file
        String[] compileCmdStr = {"clang", asmFile, "-o", outFile};
        final Process child = Runtime.getRuntime().exec(compileCmdStr, null, null);
        child.waitFor();
        // run the executable
        String[] runCmdStr = {outFile};
        final Process childRun = Runtime.getRuntime().exec(runCmdStr, null, null);
        // read stdout
        Thread stdoutThread = new Thread(() -> {
            try {
                BufferedReader reader = new BufferedReader(
                        new InputStreamReader(childRun.getInputStream()));
                String all = reader.readAllAsString();
                sb.append(all);
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
        stdoutThread.start();

        int exitCode = childRun.waitFor();
        stdoutThread.join();

        // remove, if necessary
        if (!keepAsm) {
            String[] cmdStr2 = {"rm", "-rf", asmFile};
            Process childRemove = Runtime.getRuntime().exec(cmdStr2, null, null);
            childRemove.waitFor();
        }
        return "";
    }

    public String compile(Stm prog) {
        StringBuffer sb = new StringBuffer();
        try {
            compileStm(prog, sb);
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
        return sb.toString();
    }
}
